storing details in dynamo db
Nexus-Optima/Frontend-Engine pull request #56
Opened 2024-03-19 10:53 UTC by Anikkk

2024-03-21 07:22 UTC, kaivan-s commented on src/App.js
> +        console.log(response);
Remove this line.

2024-03-21 07:22 UTC, kaivan-s commented on src/Authentication/register.js
> +    console.log(requestBody);
Remove this statement.

2024-03-21 07:23 UTC, kaivan-s commented on src/Authentication/register.js
> +      console.log('POST request successful:', data);
Remove this.

2024-03-21 07:23 UTC, kaivan-s commented on src/Dashboard/Dashboard.js
> +        console.log(userData)
Remove this.

2024-03-21 07:23 UTC, kaivan-s commented on src/Dashboard/Dashboard.js
> +      console.log(data?.username);
Remove this.

2024-03-21 07:24 UTC, kaivan-s commented on src/Dashboard/Dashboard.js
> +      if(data){
Why do we have this check here? If user is not present then we won't be able to login itself no?

2024-03-21 07:24 UTC, kaivan-s commented on src/Settings/Personal.js
> +      if (data) {
Same, why do we need this check?

2024-03-21 07:25 UTC, kaivan-s commented on src/Settings/Personal.js
> +          username: data?.username,
Does ? mean optional??

2024-03-21 07:25 UTC, kaivan-s commented on src/Settings/Personal.js
> +    console.log(formData);
Remove this.

2024-03-21 07:26 UTC, kaivan-s commented on src/api/UserDetailsService.js
> +        console.error("Error fetching user data:", error);
Instead of console.error, show the error on the page.

2024-03-21 07:26 UTC, kaivan-s commented on src/api/UserDetailsService.js
> +export const fetchUserDetails = async ({userEmail}) =>{
Change name of the folder from `api` to `Api`

2024-03-21 07:27 UTC, kaivan-s requested changes
Added a few comments. Please check.

2024-03-21 13:43 UTC, Anikkk commented
all the changes made as per the comment

2024-03-22 03:51 UTC, kaivan-s commented on src/Authentication/register.js
> +      console.error('There was an error:', error);
Show error on page instead of console.error. Clients don't use console

2024-03-22 03:51 UTC, kaivan-s commented on src/Services/UserDetailsService.js
> +        console.error("Error fetching user data:", error);
Similarly here.

2024-03-22 03:51 UTC, kaivan-s commented on src/Settings/Personal.js
> +    console.log(formData);
Please remove this log statement.

2024-03-22 03:52 UTC, kaivan-s commented on src/api/UserDetailsService.js
> +    try {
If we have created a new folder then delete this one.

2024-03-22 03:53 UTC, kaivan-s requested changes
Added a few comments. Please check.

2024-03-22 08:42 UTC, Anikkk commented on src/Authentication/register.js
> +      console.error('There was an error:', error);
![Screenshot 2024-03-22 140927](https://github.com/Nexus-Optima/Frontend-Engine/assets/43331966/ffd5f9d7-d1ff-4bcb-8b67-6334896f63e7)

for now this is the message display when error is occured, thinking to implement a custom error page where message will be displayed as per the error, once everything is completed.

2024-03-22 08:42 UTC, Anikkk commented on src/Settings/Personal.js
> +    console.log(formData);
removed

2024-03-22 08:43 UTC, Anikkk commented on src/Services/UserDetailsService.js
> +        console.error("Error fetching user data:", error);
![Screenshot 2024-03-22 141319](https://github.com/Nexus-Optima/Frontend-Engine/assets/43331966/ed35855c-cc3b-451e-862a-06776ceeb121)

2024-03-22 08:44 UTC, Anikkk commented
all the log messages have been removed and also error message is being displayed .

2024-03-26 10:33 UTC, kaivan-s approved these changes

2024-03-26 10:40 UTC, merged